#!/bin/sh

set -e

# Description:
#   Creates a link to the file and then repeatedly calls rsync --inplace until
#   the link stops existing. This means that the only way to stop the script is
#   to either kill the process or delete the autogenerated hard link that it
#   depends on.

USAGE='streamsync [-t TIMEOUT] [-o OPTIONS] FILE DEST'
if [ $# -lt 2 -o $# -gt 6 ]; then
	echo $USAGE && exit 1
fi

TIMEOUT=10
OPTIONS=""

while getopts ho:t: ARG; do
	case $ARG in
	h) echo $USAGE && exit 0 ;;
	o) OPTIONS=$OPTARG ;;
	t) TIMEOUT=$OPTARG ;;
	?) echo $USAGE; exit 1 ;;
	esac
done

shift $(( $OPTIND - 1 ))

FILE="$1"
DEST="$2"

host="$(echo "$DEST" | cut -d ':' -f 1)"

if [ '!' "$host" = "$DEST" ]; then
	# We are copying to a remote location
	ssh -MNf -O "exit" "$host"
fi

STREAM="$FILE.stream"
# TODO: use temporary files instead of this
# TODO: create an easy way to stop the sync
ln "$FILE" "$STREAM"
# TODO: don't want to defaultly name the destination file $FILE.stream
while [ -e "$STREAM" ]; do
	rsync --inplace $OPTIONS "$STREAM" "$DEST"
	sleep $TIMEOUT
done
